name: LastSeen
main: net.flare183.lastseen.LastSeen
version: 2.0

commands:
    lastseen:
        description: Displays the time at which the specified user last logged off from the server. 
        usage: /<command> <username>