name: LastSeen
main: bin.flare183.lastseen.LastSeen
version: 1.5

commands:
    lastseen:
        description: Displays the time at which the specified user last logged off from the server. 
        usage: /<command> <username>